// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvPV5W_APfyKZ7P8er_BQxPBy4EkFOfVg',
    appId: '1:63035460374:web:85749244c84cdb09981e37',
    messagingSenderId: '63035460374',
    projectId: 'professional-course-73449',
    authDomain: 'professional-course-73449.firebaseapp.com',
    storageBucket: 'professional-course-73449.firebasestorage.app',
    measurementId: 'G-REBBQZBGDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6JwqGy9FYgFV-9snY5_r3nEx5buMn4tg',
    appId: '1:63035460374:android:630dfb2c1d880c49981e37',
    messagingSenderId: '63035460374',
    projectId: 'professional-course-73449',
    storageBucket: 'professional-course-73449.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZPygc8CvQnfpKBnHqiTwoFgPpbTM2SxA',
    appId: '1:63035460374:ios:a6e5cabd2d5f5d08981e37',
    messagingSenderId: '63035460374',
    projectId: 'professional-course-73449',
    storageBucket: 'professional-course-73449.firebasestorage.app',
    iosBundleId: 'com.example.course',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZPygc8CvQnfpKBnHqiTwoFgPpbTM2SxA',
    appId: '1:63035460374:ios:a6e5cabd2d5f5d08981e37',
    messagingSenderId: '63035460374',
    projectId: 'professional-course-73449',
    storageBucket: 'professional-course-73449.firebasestorage.app',
    iosBundleId: 'com.example.course',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvPV5W_APfyKZ7P8er_BQxPBy4EkFOfVg',
    appId: '1:63035460374:web:0b15cfdf0aec3eaa981e37',
    messagingSenderId: '63035460374',
    projectId: 'professional-course-73449',
    authDomain: 'professional-course-73449.firebaseapp.com',
    storageBucket: 'professional-course-73449.firebasestorage.app',
    measurementId: 'G-2MKKP2CZQC',
  );
}
